### ISSUE TITLE
Incorrect exit status on require failure

### ISSUE THREAD

**Issue by sstarcher** [sensu-plugins/sensu-plugin#104]
When having an error on a `require` and specifying a parameter on the command line results in an exit code of 0.  You also get the same result if you have a gem load conflict with versions.  When not specifying a parameter it returns 3.  The returned status is coming from https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-plugin/cli.rb#L58

Code
```
#! /usr/bin/env ruby

require 'sensu-plugin/check/cli'
require 'timederp'

class Bad < Sensu::Plugin::Check::CLI

  option :host,
         short: '-h HOST'

  def run
  end
end
```

Results with the following output and an exit code of 0
```
Usage: /opt/sensu/embedded/bin/check-es-query-count.rb (options)
/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- timederp (LoadError)
	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /opt/sensu/embedded/bin/check-es-query-count.rb:4:in `<main>'
```

**Comment by cwjohnston** [comment]
Fixed by #121 which was released today in version 1.4.0
