### ISSUE TITLE
UX of plugin browsing

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugin#111]
I don't know where else to report a bug about this, so I'm reporting it here.

If one takes a look at http://sensu-plugins.io/plugins/ , you'll most likely end up frustrated and angry. The UX (User eXperience) is just terrible. Plugins are not categorized, not sorted alphabetically and are arranged in tiles (wtf?). Furthermore, all the plugin names on the webpage begin with "sensu-plugins-". This is redundant information that makes UX worse.

A simple solution would be to just strip "sensu-plugins-" from the beginning of names, put everything in 1 column table and sort rows alphabetically. Additionally, plugins can be categorized.

**Comment by majormoses** [comment]
@maticmeznar agreed though this is not the right place to discuss I would say this seems a more appropriate location: https://github.com/sensu-plugins/sensu-plugins.github.io @mbbroberg fyi tagging you on this as I think this is gonna be all you.

**Comment by majormoses** [comment]
I am closing this out as this is the wrong place and there are already streams of work in place to improve this. There is probably already something in https://github.com/sensu-plugins/community
