### ISSUE TITLE
Tag for v1.2.0

### ISSUE THREAD

**Issue by paramite** [sensu-plugins/sensu-plugin#112]
Please create tag for v1.2.0 (69ac44f539d07bf044eb2b1370c36230fd00524f), so that tarball can be downloaded from github. Thanks in advance

**Comment by mattyjones** [comment]
Give me 24 hours and I will do a release of a new version with a tarball. @paramite

**Comment by zbintliff** [comment]
Hey any progress on this?

**Comment by cwjohnston** [comment]
Sorry for the delay; I have now tagged it. https://github.com/sensu-plugins/sensu-plugin/tree/v1.2.0

I created a milestone to capture issues for the next release: https://github.com/sensu-plugins/sensu-plugin/milestones/v1.3.0

Lets use #113 for discussion of that work. Thanks!
