### ISSUE TITLE
Can we get a new release/tag?

### ISSUE THREAD

**Issue by zbintliff** [sensu-plugins/sensu-plugin#113]
Hey I submitted this PR a while ago: https://github.com/sensu-plugins/sensu-plugin/commit/dd2f61fcada74058f08be7736561adec70dead9f

Currently we are maintaining our our patch'ed gem but we want to maintain parity with the repo.  Can we get a release that has https support for api operations?

**Comment by zbintliff** [comment]
bump

**Comment by dmizelle** [comment]
Please, we could _really_ use a new version.

**Comment by zbintliff** [comment]
Just bumping this to show still hoping for a release.

**Comment by cwjohnston** [comment]
Thank you for your forbearance. We released v1.3.0 today! :shipit:
