### ISSUE TITLE
Sensu - Handler type set subdue does not work

### ISSUE THREAD

**Issue by h2aguilar** [sensu-plugins/sensu-plugin#119]
Hey Guys, I was trying to implement a subdue for a handler of type set:

"appsupport_bh": {
      "type": "set",
      "handlers": [
        "appsupport_email",
        "appsupport_sms"
      ],
      "subdue": {
        "at": "handler",
        "days": [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday"
        ],
        "begin": "7AM",
        "end": "7PM"
      }

But it doesn't seem to work does subdue only work with handlers and not in handler group?

**Comment by cwjohnston** [comment]
Hi @h2aguilar thanks for raising this concern. I can see how subduing the entire set may be desirable but this currently expected behavior. 

Attributes defined on handler sets are not applied to the handlers they contain. I'll ensure we update the documentation to note this.
