### ISSUE TITLE
README.md duplicate

### ISSUE THREAD

**Issue by davidfox2** [sensu-plugins/sensu-plugin#140]
the instructions:
```
Sensu's configuration settings are available with the settings method (they will be loaded on first use). We recommend you put your settings in a JSON file in /etc/sensu/conf.d, with a unique top-level key, like:

{
  "mymutator": {
    "foo": true
  }
}
```
are repeated twice in the readme, in both handlers and mutators is this supposed to be this way?

**Comment by cwjohnston** [comment]
@davidfox2 I believe the intent here is to illustrate that the different types of plugins which this library provides base classes for (e.g. checks, handlers, mutators) all have access to Sensu settings and should take care to define their own top-level name space or scope for their configuration (e.g. `mycheck` and `mymutaor` are the top-level name spaces in the two examples you mention).

We can probably describe this more succinctly and avoid the repetition.

**Comment by cwjohnston** [comment]
@davidfox2 would you mind reviewing proposed change in #143 to see if that makes more sense?

**Comment by davidfox2** [comment]
That makes much more sense! Thanks!
