### ISSUE TITLE
Support for Ruby < 2.0.0

### ISSUE THREAD

**Issue by vpjapp-avoltus** [sensu-plugins/sensu-plugin#148]
Hello,

I'm having problems installing sensu-plugin with Ruby 1.9.

The commit https://github.com/sensu-plugins/sensu-plugin/commit/229702db7ac98294bd2ae3b2b3195c1ce8f05438 states in the comment that the version of json be pinned to <2.0.0 but the code defines <=2.0.0 which allows for 2.0.0 which does not seem to work with Ruby < 2.0.

In rubygems it's stated that with C-version of json 2.0 depends on Ruby 2.0 while JRuby version does not. Go figure.
https://rubygems.org/gems/json/versions/2.0.0 vs https://rubygems.org/gems/json/versions/2.0.0-java

**Comment by vpjapp-avoltus** [comment]
Just a note to others possibly suffering from this:
As a workaround installing json-gem version 1.8.3 before installing sensu-plugin worked at least for me.

**Comment by cwjohnston** [comment]
Hi @vpjapp-avoltus, thanks for opening this issue. As the commit message states, the intent was to pin at `< 2.0.0` and it seems this was overlooked.
