### ISSUE TITLE
Global deprecated filtering settings

### ISSUE THREAD

**Issue by portertech** [sensu-plugins/sensu-plugin#166]
From: https://github.com/sensu/sensu/issues/1530

the settings of the "deprecated filtering" should have a global server setting

## Expected Behavior
Be able to set a global server setting to disable the deprecated filtering

## Current Behavior
currently the settings needs to be in many places to completely bypass de deprecated filtering

- in checks
- in client config for the keepalive event
- in all manual tcp socket events

## Your Environment
* Sensu version used: 0.26.3

**Comment by xblitz** [comment]
this should only be while the feature is still there, so it can be disabled as a whole

**Comment by cwjohnston** [comment]
this feature is included in sensu-plugin 1.4.5, now available on rubygems.org
