### ISSUE TITLE
Check failed to run: execution expired

### ISSUE THREAD

**Issue by dhdanno** [sensu-plugins/sensu-plugin#176]
We still see this issue occasionally even after upgrading to sensu 1.0, sensu-plugin-1.4.5 with http-2.5.0

Check failed to run: execution expired, [
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/check/cli.rb:23:in `write'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/check/cli.rb:23:in `puts'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/check/cli.rb:23:in `puts'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/check/cli.rb:23:in `output'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:29:in `block (2 levels) in <class:CLI>'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-http-2.5.0/bin/check-http.rb:242:in `rescue in run'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-http-2.5.0/bin/check-http.rb:237:in `run'\", 
 \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'\"]
 \n","status":2

This check took 15 seconds to run. Should have taken less than 1

**Comment by majormoses** [comment]
@dhdanno unless I am missing something I don't think this is the right repo to report this, let's move it to https://github.com/sensu-plugins/sensu-plugins-http.

Another few notes:
- I don't think this does have to do with versions in this case as I recall seeing similar issues with older and newer versions of sensu. But assuming it does we are in maintenance mode trying to get all all the plugins working with ruby 2.4 (which is the embedded version in sensu 0.29+) which you can read more about here: https://blog.sensuapp.org/community-maintenance-mode-d109e75bcbc4 if you are looking for stable I would recommend pinning on 0.28 for now.

**Comment by majormoses** [comment]
likely related issues:
- https://github.com/sensu-plugins/sensu-plugins-http/issues/46
- https://github.com/sensu-plugins/sensu-plugins-http/issues/37

**Comment by dhdanno** [comment]
Thanks. New issue here: https://github.com/sensu-plugins/sensu-plugins-http/issues/82
