### ISSUE TITLE
Support output formats in a base class for sensu-plugin CLI

### ISSUE THREAD

**Issue by grepory** [sensu-plugins/sensu-plugin#37]
We'd like to be able to flip output formats on a whim. Something like what I've suggested here:

https://github.com/grepory/sensu-plugin/blob/json_output/lib/sensu-plugin/metric/cli.rb

Unfortunately, mixlib::cli doesn't allow us to inherit options, so currently this would require monkey patching to use. That's, obviously, not good.

I'd like to propose that either:
- mixlib::cli gets fixed, and we use (something like) what I've proposed, where metrics checks inherit Sensu::Plugin::Metric::CLI (and get the --json, --opentsdb, and --graphite) output format options.
- this is handled some other way, like Sensu::Plugin::Metric::CLI modifies ARGV to parse out the output type options and then passes everything else to parse_options.

**Comment by mattyjones** [comment]
@grepory 
Can you confirm that this is still and issue and if so I can poke around and see what I can come up with.

Thanks

**Comment by grepory** [comment]
The pull request to fix this in mixlib-cli has been open for almost 2 years.

https://github.com/chef/mixlib-cli/pull/13

**Comment by majormoses** [comment]
@grepory looks like its merged now, I know that it's been a while...are you still interested in submitting a PR?

**Comment by luisdavim** [comment]
I like this idea but I see some things I think @grepory's approach is missing:
- We should support as "source format" the currently supported formats no to break compatibility with existing plugins, not just Graphite.
- We should consider formats that include tags, like dogStatsd, influxDB, Prometheus, etc.

**Comment by grepory** [comment]
Oh wow. It has been a long time since I've seen this.

This isn't intended to be used as a mutator, only as a check. So, for example, in your plugin you would generate metrics in some standardized format and then sensu-plugin would be responsible for mutating to the output you would want.

I think adding additional formats is orthogonal to the concern of this issue. This was just about making the writing of metrics plugins easier.

**Comment by grepory** [comment]
@majormoses I proooobably won't have time to take a stab at this, as I've been focused on a lot of other Sensu things and haven't looked at the Ruby stuff in a while. Anyway, that's my braindump of what this issue was originally about.

**Comment by majormoses** [comment]
fair enough, I don't have the bandwidth right now to take this either, It's a cool idea so lets keep it open and maybe someone who has a need will volunteer.

**Comment by cwjohnston** [comment]
FWIW this feature request sort of seems to describe the existing Sensu Enterprise [output_format mutator](https://sensuapp.org/docs/latest/enterprise/built-in-mutators.html#output-format).

**Comment by majormoses** [comment]
closed in #185 and released in https://rubygems.org/gems/sensu-plugin/versions/2.4.0 

Huzzah for closing old requests!
