### ISSUE TITLE
"resolve" events being filtered by occurrences? 

### ISSUE THREAD

**Issue by skymob** [sensu-plugins/sensu-plugin#47]
Today I observed a resolved event not being passed to handlers. Here's a [gist of sample sensu-server.log output](https://gist.github.com/skymob/1c3aa01fdb013d80bbec), it looks like the event is being filtered because right after the resolution event, we see two "not enough occurrences" messages. 

Sensu-plugin version 0.1.7

**Comment by kshep** [comment]
@portertech Am I missing something, or did https://github.com/sensu-plugins/sensu-plugin/pull/50 break this again?
