### ISSUE TITLE
In event_summary(), trim by nil by default

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu-plugins/sensu-plugin#75]
Trimming by 100 chars seems arbitrary, and it can cause issues with some combination of plugins. E.g.:

https://github.com/sensu/sensu-community-plugins/commit/1398e6c0323babb0178881106f61dc06561aeaa9

It's best to trim by nil by default, and let handlers choose their own trim limit.

(This was the outcome of a discussion on IRC with portertech on 2014/10/06)

**Comment by mattyjones** [comment]
@FlorinAndrei 

Sorry for the delay. If you have the time and ability could you please open a PR for this and we will gladly take a look at it.

Thanks

**Comment by FlorinAndrei** [comment]
I'm not sure I have the time, I'm not focused on Sensu these days that much.

**Comment by majormoses** [comment]
This is very old and pagerfuty has its own repo now, we should close or move this over.

**Comment by cwjohnston** [comment]
Closing as this seems like a breaking change and isn’t likely to be implemented at this time. Handler plugins may choose to implement their own event summary methods in cases where the existing behavior is problematic.
