### ISSUE TITLE
silence specific status only

### ISSUE THREAD

**Issue by petere** [sensu-plugins/sensu-plugin#77]
I would like to have a way to silence a check for a specific status only.  This would allow a kind of "acknowledge" facility.  For example, when a check produces a warning, I would like to to be able to silence that, but be re-alerted when it changes to critical.  I think this could be implemented easily by putting a standardized field into the `silence` stash, like `{"status": 1}`.  Comments?

**Comment by mattyjones** [comment]
@petere 

Sorry for the delay. if I were going to implement something like this I would not do it at the plugin level.  I would this this should be a feature either in the dashboard or in the api as that is what create the stash.

**Comment by majormoses** [comment]
very old issue...given the lack of interest on this I don't see anyone jumping on this but I think there is value in keeping it open as someone else might want to keep it.

**Comment by cwjohnston** [comment]
Because silencing is now a native concept in Sensu, and handlers can opt-in to handling silenced events, I’m going to go ahead and close this issue.
