### ISSUE TITLE
OMD - The Open Monitoring Distribution sensu-plugin

### ISSUE THREAD

**Issue by topstarnetwork** [sensu-plugins/sensu-plugin#80]
Hello,
I would like ot know if you have a OMD - The Open Monitoring Distribution http://omdistro.org/start  http://mathias-kettner.com/index.html sensu-plugin instead of the simple nagios sensu-plugin?????

Regards, Heather

**Comment by mattyjones** [comment]
@topstarnetwork 

What are you looking for a plugin that can be installed with OMD or something else?

Thanks

**Comment by topstarnetwork** [comment]
Yes I was wondering if sensu has a OMD - The Open Monitoring Distribution lugin as it seems omd has more features then nagios itself,
thanks, Heather

**Comment by mattyjones** [comment]
@topstarnetwork 

No not at this time, I will add to the roadmap for possible exploration and discussion though.

Thanks for your thoughts
