### ISSUE TITLE
Feature request: Output formatting for check scripts

### ISSUE THREAD

**Issue by roobert** [sensu-plugins/sensu-plugin#92]
Along the same vein as #37, I'd like to be able to choose how messages are formatted for all checks that inherit from sensu-plugin, possibly some kind of global configuration file?

**Comment by roobert** [comment]
Wouldn't changing the default format of check script messages be better done using a mutator, at least that way it'd be customizable..?

**Comment by luisdavim** [comment]
I think that #185 covers this.

**Comment by majormoses** [comment]
closed via #185 and released in https://rubygems.org/gems/sensu-plugin/versions/2.4.0

If you feel that this does not address your issue please reply back and we can discuss it.
