### ISSUE TITLE
Make a sensu-plugin release for 1.2.0 here on github

### ISSUE THREAD

**Issue by ngrennan-inflection** [sensu-plugins/sensu-plugin#96]
I needed 1.2.0, but didn't know it. I looked at the release section and only saw 1.1.0. Later I went to rubygems.org and found 1.2.0. Then noticed mention of 1.2.0 in the file comments of the repo.

**Comment by zbintliff** [comment]
I also spent a ton of time looking at master, assuming that was 1.2.0 because no 1.2.0 tag existed. Please just tag the commit of 1.2.0 release.

**Comment by zbintliff** [comment]
Here is the Commit

**Comment by petere** [comment]
I got confused by this as well. Please create a tag for 1.2.0.

**Comment by cwjohnston** [comment]
Sorry for the inconvenience, we missed the mark here. I've tagged the commit https://github.com/sensu-plugins/sensu-plugin/tree/v1.2.0
