### ISSUE TITLE
hardcoded timeout is hardcoded

### ISSUE THREAD

**Issue by jaxxstorm** [sensu-plugins/sensu-plugin#99]
The timeout in sensu-plugin is hardcoded to 2 here: https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L134

Unfortunately, our sensu setup is rather large, and it often takes longer than 2 seconds for the API to return a result:

```
time curl -u admin http://localhost:4567/stashes/silence/hostname
Enter host password for user 'admin':
{"reason":"testhost","source":"uchiwa","timestamp":1442276921.0}
real	0m2.895s
user	0m0.004s
sys	0m0.001s
```

As a result, we're seeing a lot of this in our sensu-server logs:

```
"output": [
    "timed out while attempting to query the sensu api for a stash\n",
```

I can obviously override this method in our handlers, but we should still be able to configure this more accurately be default. In any case, 2s is very very low

**Comment by analytically** [comment]
I've increased this to 5 seconds until there's a better solution.
